name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:   

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      threads1:
        image: textile/go-threads:latest
        env:
          THRDS_HOSTADDR: /ip4/0.0.0.0/tcp/4006
          THRDS_APIADDR: /ip4/0.0.0.0/tcp/6006
          THRDS_APIPROXYADDR: /ip4/0.0.0.0/tcp/6007
          THRDS_DEBUG: true
        ports:
          - '4006:4006'
          - '127.0.0.1:6006:6006'
          - '127.0.0.1:6007:6007'
      threads2:
        image: textile/go-threads:latest
        env:
          THRDS_HOSTADDR: /ip4/0.0.0.0/tcp/4006
          THRDS_APIADDR: /ip4/0.0.0.0/tcp/6006
          THRDS_APIPROXYADDR: /ip4/0.0.0.0/tcp/6007
          THRDS_DEBUG: true
        ports:
          - '4206:4006'
          - '127.0.0.1:6206:6006'
          - '127.0.0.1:6207:6007'

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.2.20479.15
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
